In [1]:
!pip install kaggle kagglehub

Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (9.0.0)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (2026.7.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.8)

In [15]:
from google.colab import files
files.upload()

Saving U8_Data_Cleaning_Part2_Lab.ipynb to U8_Data_Cleaning_Part2_Lab.ipynb

{'U8_Data_Cleaning_Part2_Lab.ipynb': b'{\n  "nbformat": 4,\n  "nbformat_minor": 0,\n  "metadata": {\n    "colab": {\n      "provenance": []\n    },\n    "kernelspec": {\n      "name": "python3",\n      "display_name": "Python 3"\n    },\n    "language_info": {\n      "name": "python"\n    }\n  },\n  "cells": [\n    {\n      "cell_type": "code",\n      "source": [\n        "# Core imports for the whole lab\\n",\n        "import numpy as np\\n",\n        "import pandas as pd\\n",\n        "\\n",\n        "pd.set_option(\'display.max_columns\', None)\\n",\n        "print(\'Setup complete. pandas\', pd.__version__)"\n      ],\n      "metadata": {\n        "colab": {\n          "base_uri": "https://localhost:8080/"\n        },\n        "id": "GJJe_30tpUg8",\n        "outputId": "fd4cf9b6-7ad9-4a29-8c7f-0064ec848b65"\n      },\n      "execution_count": null,\n      "outputs": [\n        {\n          "output_type": "stream",\n          "name": "stdout",\n          "text": [\n            "Setup complete. pandas 2.2.3\\n"\n          ]\n        }\n      ]\n    },\n    {\n      "cell_type": "code",\n      "source": [\n        "# -----------------------------------------------------------\\n",\n        "# A SMALL, ALREADY-CLEAN DATASET (Part 1 did the cleaning)\\n",\n        "# -----------------------------------------------------------\\n",\n        "# Mixed columns: an unordered category (city), an ordered category\\n",\n        "# (size), two numeric features on very different scales, and a target.\\n",\n        "df = pd.DataFrame({\\n",\n        "    \'city\':   [\'pune\', \'delhi\', \'mumbai\', \'pune\', \'delhi\', \'mumbai\', \'pune\', \'delhi\'],\\n",\n        "    \'size\':   [\'small\', \'large\', \'medium\', \'medium\', \'small\', \'large\', \'large\', \'small\'],\\n",\n        "    \'age\':    [25, 41, 33, 29, 52, 38, 46, 22],\\n",\n        "    \'income\': [38000, 92000, 55000, 47000, 120000, 76000, 88000, 41000],\\n",\n        "    \'bought\': [0, 1, 0, 0, 1, 1, 1, 0],   # target\\n",\n        "})\\n",\n        "df"\n      ],\n      "metadata": {\n        "colab": {\n          "base_uri": "https://localhost:8080/",\n          "height": 300\n        },\n        "id": "KaOdqgYMpVaE",\n        "outputId": "c6f512cf-7102-445e-8d0e-b58e3c9e2154"\n      },\n      "execution_count": null,\n      "outputs": [\n        {\n          "output_type": "execute_result",\n          "data": {\n            "text/plain": [\n              "     city    size  age  income  bought\\n",\n              "0    pune   small   25   38000       0\\n",\n              "1   delhi   large   41   92000       1\\n",\n              "2  mumbai  medium   33   55000       0\\n",\n              "3    pune  medium   29   47000       0\\n",\n              "4   delhi   small   52  120000       1\\n",\n              "5  mumbai   large   38   76000       1\\n",\n              "6    pune   large   46   88000       1\\n",\n              "7   delhi   small   22   41000       0"\n            ],\n            "text/html": [\n              "\\n",\n              "  <div id=\\"df-0acf0477-9e04-4ba9-998a-2f122d58b837\\" class=\\"colab-df-container\\">\\n",\n              "    <div>\\n",\n              "<style scoped>\\n",\n              "    .dataframe tbody tr th:only-of-type {\\n",\n              "        vertical-align: middle;\\n",\n              "    }\\n",\n              "\\n",\n              "    .dataframe tbody tr th {\\n",\n              "        vertical-align: top;\\n",\n              "    }\\n",\n              "\\n",\n              "    .dataframe thead th {\\n",\n              "        text-align: right;\\n",\n              "    }\\n",\n              "</style>\\n",\n              "<table border=\\"1\\" class=\\"dataframe\\">\\n",\n              "  <thead>\\n",\n              "    <tr style=\\"text-align: right;\\">\\n",\n              "      <th></th>\\n",\n              "      <th>city</th>\\n",\n              "      <th>size</th>\\n",\n              "      <th>age</th>\\n",\n              "      <th>income</th>\\n",\n              "      <th>bought</th>\\n",\n              "    </tr>\\n",\n              "  </thead>\\n",\n              "  <tbody>\\n",\n              "    <tr>\\n",\n              "      <th>0</th>\\n",\n              "      <td>pune</td>\\n",\n              "      <td>small</td>\\n",\n              "      <td>25</td>\\n",\n              "      <td>38000</td>\\n",\n              "      <td>0</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>1</th>\\n",\n              "      <td>delhi</td>\\n",\n              "      <td>large</td>\\n",\n              "      <td>41</td>\\n",\n              "      <td>92000</td>\\n",\n              "      <td>1</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>2</th>\\n",\n              "      <td>mumbai</td>\\n",\n              "      <td>medium</td>\\n",\n              "      <td>33</td>\\n",\n              "      <td>55000</td>\\n",\n              "      <td>0</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>3</th>\\n",\n              "      <td>pune</td>\\n",\n              "      <td>medium</td>\\n",\n              "      <td>29</td>\\n",\n              "      <td>47000</td>\\n",\n              "      <td>0</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>4</th>\\n",\n              "      <td>delhi</td>\\n",\n              "      <td>small</td>\\n",\n              "      <td>52</td>\\n",\n              "      <td>120000</td>\\n",\n              "      <td>1</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>5</th>\\n",\n              "      <td>mumbai</td>\\n",\n              "      <td>large</td>\\n",\n              "      <td>38</td>\\n",\n              "      <td>76000</td>\\n",\n              "      <td>1</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>6</th>\\n",\n              "      <td>pune</td>\\n",\n              "      <td>large</td>\\n",\n              "      <td>46</td>\\n",\n              "      <td>88000</td>\\n",\n              "      <td>1</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>7</th>\\n",\n              "      <td>delhi</td>\\n",\n              "      <td>small</td>\\n",\n              "      <td>22</td>\\n",\n              "      <td>41000</td>\\n",\n              "      <td>0</td>\\n",\n              "    </tr>\\n",\n              "  </tbody>\\n",\n              "</table>\\n",\n              "</div>\\n",\n              "    <div class=\\"colab-df-buttons\\">\\n",\n              "\\n",\n              "  <div class=\\"colab-df-container\\">\\n",\n              "    <button class=\\"colab-df-convert\\" onclick=\\"convertToInteractive(\'df-0acf0477-9e04-4ba9-998a-2f122d58b837\')\\"\\n",\n              "            title=\\"Convert this dataframe to an interactive table.\\"\\n",\n              "            style=\\"display:none;\\">\\n",\n              "\\n",\n              "  <svg xmlns=\\"http://www.w3.org/2000/svg\\" height=\\"24px\\" viewBox=\\"0 -960 960 960\\">\\n",\n              "    <path d=\\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\\"/>\\n",\n              "  </svg>\\n",\n              "    </button>\\n",\n              "\\n",\n              "  <style>\\n",\n              "    .colab-df-container {\\n",\n              "      display:flex;\\n",\n              "      gap: 12px;\\n",\n              "    }\\n",\n              "\\n",\n              "    .colab-df-convert {\\n",\n              "      background-color: #E8F0FE;\\n",\n              "      border: none;\\n",\n              "      border-radius: 50%;\\n",\n              "      cursor: pointer;\\n",\n              "      display: none;\\n",\n              "      fill: #1967D2;\\n",\n              "      height: 32px;\\n",\n              "      padding: 0 0 0 0;\\n",\n              "      width: 32px;\\n",\n              "    }\\n",\n              "\\n",\n              "    .colab-df-convert:hover {\\n",\n              "      background-color: #E2EBFA;\\n",\n              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\\n",\n              "      fill: #174EA6;\\n",\n              "    }\\n",\n              "\\n",\n              "    .colab-df-buttons div {\\n",\n              "      margin-bottom: 4px;\\n",\n              "    }\\n",\n              "\\n",\n              "    [theme=dark] .colab-df-convert {\\n",\n              "      background-color: #3B4455;\\n",\n              "      fill: #D2E3FC;\\n",\n              "    }\\n",\n              "\\n",\n              "    [theme=dark] .colab-df-convert:hover {\\n",\n              "      background-color: #434B5C;\\n",\n              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\\n",\n              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\\n",\n              "      fill: #FFFFFF;\\n",\n              "    }\\n",\n              "  </style>\\n",\n              "\\n",\n              "    <script>\\n",\n              "      const buttonEl =\\n",\n              "        document.querySelector(\'#df-0acf0477-9e04-4ba9-998a-2f122d58b837 button.colab-df-convert\');\\n",\n              "      buttonEl.style.display =\\n",\n              "        google.colab.kernel.accessAllowed ? \'block\' : \'none\';\\n",\n              "\\n",\n              "      async function convertToInteractive(key) {\\n",\n              "        const element = document.querySelector(\'#df-0acf0477-9e04-4ba9-998a-2f122d58b837\');\\n",\n              "        const dataTable =\\n",\n              "          await google.colab.kernel.invokeFunction(\'convertToInteractive\',\\n",\n              "                                                    [key], {});\\n",\n              "        if (!dataTable) return;\\n",\n              "\\n",\n              "        const docLinkHtml = \'Like what you see? Visit the \' +\\n",\n              "          \'<a target=\\"_blank\\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>\'\\n",\n              "          + \' to learn more about interactive tables.\';\\n",\n              "        element.innerHTML = \'\';\\n",\n              "        dataTable[\'output_type\'] = \'display_data\';\\n",\n              "        await google.colab.output.renderOutput(dataTable, element);\\n",\n              "        const docLink = document.createElement(\'div\');\\n",\n              "        docLink.innerHTML = docLinkHtml;\\n",\n              "        element.appendChild(docLink);\\n",\n              "      }\\n",\n              "    </script>\\n",\n              "  </div>\\n",\n              "\\n",\n              "\\n",\n              "  <div id=\\"id_130ec045-b6ee-4aa8-b448-6acd3c1ac53b\\">\\n",\n              "    <style>\\n",\n              "      .colab-df-generate {\\n",\n              "        background-color: #E8F0FE;\\n",\n              "        border: none;\\n",\n              "        border-radius: 50%;\\n",\n              "        cursor: pointer;\\n",\n              "        display: none;\\n",\n              "        fill: #1967D2;\\n",\n              "        height: 32px;\\n",\n              "        padding: 0 0 0 0;\\n",\n              "        width: 32px;\\n",\n              "      }\\n",\n              "\\n",\n              "      .colab-df-generate:hover {\\n",\n              "        background-color: #E2EBFA;\\n",\n              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\\n",\n              "        fill: #174EA6;\\n",\n              "      }\\n",\n              "\\n",\n              "      [theme=dark] .colab-df-generate {\\n",\n              "        background-color: #3B4455;\\n",\n              "        fill: #D2E3FC;\\n",\n              "      }\\n",\n              "\\n",\n              "      [theme=dark] .colab-df-generate:hover {\\n",\n              "        background-color: #434B5C;\\n",\n              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\\n",\n              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\\n",\n              "        fill: #FFFFFF;\\n",\n              "      }\\n",\n              "    </style>\\n",\n              "    <button class=\\"colab-df-generate\\" onclick=\\"generateWithVariable(\'df\')\\"\\n",\n              "            title=\\"Generate code using this dataframe.\\"\\n",\n              "            style=\\"display:none;\\">\\n",\n              "\\n",\n              "  <svg xmlns=\\"http://www.w3.org/2000/svg\\" height=\\"24px\\"viewBox=\\"0 0 24 24\\"\\n",\n              "       width=\\"24px\\">\\n",\n              "    <path d=\\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\\"/>\\n",\n              "  </svg>\\n",\n              "    </button>\\n",\n              "    <script>\\n",\n              "      (() => {\\n",\n              "      const buttonEl =\\n",\n              "        document.querySelector(\'#id_130ec045-b6ee-4aa8-b448-6acd3c1ac53b button.colab-df-generate\');\\n",\n              "      buttonEl.style.display =\\n",\n              "        google.colab.kernel.accessAllowed ? \'block\' : \'none\';\\n",\n              "\\n",\n              "      buttonEl.onclick = () => {\\n",\n              "        google.colab.notebook.generateWithVariable(\'df\');\\n",\n              "      }\\n",\n              "      })();\\n",\n              "    </script>\\n",\n              "  </div>\\n",\n              "\\n",\n              "    </div>\\n",\n              "  </div>\\n"\n            ],\n            "application/vnd.google.colaboratory.intrinsic+json": {\n              "type": "dataframe",\n              "variable_name": "df",\n              "summary": "{\\n  \\"name\\": \\"df\\",\\n  \\"rows\\": 8,\\n  \\"fields\\": [\\n    {\\n      \\"column\\": \\"city\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"category\\",\\n        \\"num_unique_values\\": 3,\\n        \\"samples\\": [\\n          \\"pune\\",\\n          \\"delhi\\",\\n          \\"mumbai\\"\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    },\\n    {\\n      \\"column\\": \\"size\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"category\\",\\n        \\"num_unique_values\\": 3,\\n        \\"samples\\": [\\n          \\"small\\",\\n          \\"large\\",\\n          \\"medium\\"\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    },\\n    {\\n      \\"column\\": \\"age\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"number\\",\\n        \\"std\\": 10,\\n        \\"min\\": 22,\\n        \\"max\\": 52,\\n        \\"num_unique_values\\": 8,\\n        \\"samples\\": [\\n          41,\\n          38,\\n          25\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    },\\n    {\\n      \\"column\\": \\"income\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"number\\",\\n        \\"std\\": 29183,\\n        \\"min\\": 38000,\\n        \\"max\\": 120000,\\n        \\"num_unique_values\\": 8,\\n        \\"samples\\": [\\n          92000,\\n          76000,\\n          38000\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    },\\n    {\\n      \\"column\\": \\"bought\\",\\n      \\"properties\\": {\\n        \\"dtype\\": \\"number\\",\\n        \\"std\\": 0,\\n        \\"min\\": 0,\\n        \\"max\\": 1,\\n        \\"num_unique_values\\": 2,\\n        \\"samples\\": [\\n          1,\\n          0\\n        ],\\n        \\"semantic_type\\": \\"\\",\\n        \\"description\\": \\"\\"\\n      }\\n    }\\n  ]\\n}"\n            }\n          },\n          "metadata": {},\n          "execution_count": 37\n        }\n      ]\n    },\n    {\n      "cell_type": "markdown",\n      "source": [\n        "1. Encoding categorical data"\n      ],\n      "metadata": {\n        "id": "TRthgG5ipaa8"\n      }\n    },\n    {\n      "cell_type": "code",\n      "source": [\n        "# -----------------------------------------------------------\\n",\n        "# \xf0\x9f\x94\xb9 1A. ONE-HOT ENCODING (for UNORDERED categories)\\n",\n        "# -----------------------------------------------------------\\n",\n        "\\n",\n        "# \'city\' has no natural order -> one 0/1 column per category\\n",\n        "city_ohe = pd.get_dummies(df[\'city\'], prefix=\'city\').astype(int)\\n",\n        "city_ohe\\n",\n        "\\n"\n      ],\n      "metadata": {\n        "colab": {\n          "base_uri": "https://localhost:8080/",\n          "height": 300\n        },\n        "id": "9dLyZnW9peC8",\n        "outputId": "d44afbfb-e801-4d14-9f20-f68925dbb401"\n      },\n      "execution_count": null,\n      "outputs": [\n        {\n          "output_type": "execute_result",\n          "data": {\n            "text/plain": [\n              "   city_delhi  city_mumbai  city_pune\\n",\n              "0           0            0          1\\n",\n              "1           1            0          0\\n",\n              "2           0            1          0\\n",\n              "3           0            0          1\\n",\n              "4           1            0          0\\n",\n              "5           0            1          0\\n",\n              "6           0            0          1\\n",\n              "7           1            0          0"\n            ],\n            "text/html": [\n              "\\n",\n              "  <div id=\\"df-d0d371ee-de31-4507-be41-f0998f40703b\\" class=\\"colab-df-container\\">\\n",\n              "    <div>\\n",\n              "<style scoped>\\n",\n              "    .dataframe tbody tr th:only-of-type {\\n",\n              "        vertical-align: middle;\\n",\n              "    }\\n",\n              "\\n",\n              "    .dataframe tbody tr th {\\n",\n              "        vertical-align: top;\\n",\n              "    }\\n",\n              "\\n",\n              "    .dataframe thead th {\\n",\n              "        text-align: right;\\n",\n              "    }\\n",\n              "</style>\\n",\n              "<table border=\\"1\\" class=\\"dataframe\\">\\n",\n              "  <thead>\\n",\n              "    <tr style=\\"text-align: right;\\">\\n",\n              "      <th></th>\\n",\n              "      <th>city_delhi</th>\\n",\n              "      <th>city_mumbai</th>\\n",\n              "      <th>city_pune</th>\\n",\n              "    </tr>\\n",\n              "  </thead>\\n",\n              "  <tbody>\\n",\n              "    <tr>\\n",\n              "      <th>0</th>\\n",\n              "      <td>0</td>\\n",\n              "      <td>0</td>\\n",\n              "      <td>1</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>1</th>\\n",\n              "      <td>1</td>\\n",\n              "      <td>0</td>\\n",\n              "      <td>0</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>2</th>\\n",\n              "      <td>0</td>\\n",\n              "      <td>1</td>\\n",\n              "      <td>0</td>\\n",\n              "    </tr>\\n",\n              "    <tr>\\n",\n              "      <th>3</th>\\n",\n              "      <td>0</td>\\n

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory

In [4]:
!kaggle datasets download -d heptapod/titanic

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/heptapod/titanic
License(s): DbCL-1.0
Downloading titanic.zip to /content
100% 10.8k/10.8k [00:00<00:00, 14.8MB/s]

In [6]:
import zipfile

with zipfile.ZipFile("titanic.zip", 'r') as zip_ref:
    zip_ref.extractall("dataset")

In [7]:
import pandas as pd

df = pd.read_csv("dataset/train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [8]:
import kagglehub

path = kagglehub.dataset_download("heptapod/titanic")

print("Dataset downloaded to:", path)

Downloading to /root/.cache/kagglehub/datasets/heptapod/titanic/1.archive...

100%|██████████| 10.8k/10.8k [00:00<00:00, 19.8MB/s]

Extracting files...
Dataset downloaded to: /root/.cache/kagglehub/datasets/heptapod/titanic/versions/1

In [9]:
import pandas as pd

df = pd.read_csv(path + "/train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [14]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [11]:
import requests
import pandas as pd

url = "https://api.exchangerate-api.com/v4/latest/USD"

response = requests.get(url)
data = response.json()

rates = data["rates"]

df = pd.DataFrame(list(rates.items()), columns=["Currency","Rate"])
df.head()

  Currency    Rate
0      USD    1.00
1      AED    3.67
2      AFN   64.77
3      ALL   81.40
4      AMD  363.45

In [12]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bank.db")

data = {
    "Customer_ID":[1,2,3,4],
    "Loan_Amount":[200000,150000,300000,180000],
    "Credit_Score":[720,680,650,700]
}

df = pd.DataFrame(data)

df.to_sql("customers", conn, if_exists="replace", index=False)

4

In [13]:
query = "SELECT * FROM customers"

df = pd.read_sql(query, conn)
df.head()

   Customer_ID  Loan_Amount  Credit_Score
0            1       200000           720
1            2       150000           680
2            3       300000           650
3            4       180000           700